import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                fontSize: '18px',         // Increased font size
                padding: '24px 32px',     // Increased padding (top/bottom left/right)
                maxWidth: '600px',        // Allow it to grow wider
                minWidth: '300px',        // Ensure it's never too small
                borderRadius: '12px',     // Slightly rounder corners look better at large sizes
              },
              success: {
                style: {
                  border: '2px solid #22c55e', // Thicker border for better visibility
                  background: '#f0fdf4',       // Light green background
                  color: '#15803d',            // Dark green text
                },
                iconTheme: {
                  primary: '#22c55e',
                  secondary: '#fff',
                },
              },
              error: {
                style: {
                  border: '2px solid #ef4444',
                  background: '#fef2f2',       // Light red background
                  color: '#b91c1c',            // Dark red text
                },
                iconTheme: {
                  primary: '#ef4444',
                  secondary: '#fff',
                },
              },
            }}
          />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}